---
spring:
  application.name: sample-boot-hibernate
  aop.proxy-target-class: true
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  messages.basename: messages-validation, messages
  cache.jcache.config: ehcache.xml
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
  http.multipart:
    max-file-size: 20MB
    max-request-size: 20MB

banner.location: banner.txt

server:
  port: 8080
  error:
    whitelabel.enabled: false
    path: /api/error

security:
  basic.enabled: false
  user.password: unused 

management:
  context-path: /api/management
  security.enabled: false
  health:
    diskspace.enabled: true
    db.enabled: true

extension:
  datasource:
    default:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username:
      password:
    system:
      url: jdbc:h2:mem:system;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username:
      password:
  hibernate:
    default:
      dialect: org.hibernate.dialect.H2Dialect
      packageToScan: sample.model
      showSql: true
      createDrop: true
    system:
      dialect: org.hibernate.dialect.H2Dialect
      packageToScan: sample.context
      showSql: true
      createDrop: true
  security:
    auth:
      enabled: false
      admin: false
    cors.enabled: true
  mail.enabled: false
  datafixture.enabled: true

---
spring:
  profiles: production

management.security.enabled: true

extension:
  datasource:
    default:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@xxx.xxx.xxx.xxx:1521:xx
      username: XXXXXX
      password: XXXXXX
    system:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@xxx.xxx.xxx.xxx:1521:xx
      username: XXXXXX
      password: XXXXXX
  hibernate:
    default:
      dialect: org.hibernate.dialect.Oracle10gDialect
      showSql: false
      createDrop: false
    system:
      dialect: org.hibernate.dialect.Oracle10gDialect
      showSql: false
      createDrop: false
  security:
    auth.enabled: true
    cors.enabled: false
  datafixture.enabled: false

---
spring:
  profiles: admin

server.port: 8081

extension: 
  security.auth.admin: true
