---
spring:
  application.name: ddd-java
  aop.proxy-target-class: true
  messages.basename: messages-validation, messages
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
    serialization:
      indent_output: true
      write_dates_as_timestamps: false

server.port: 8080

error:
  whitelabel.enabled: false
  path: /api/error

security.basic.enabled: false

multipart:
  maxFileSize: 20MB
  maxRequestSize: 20MB

management:
  context-path: /api/management
  security.enabled: false
  health:
    diskspace.enabled: true
    db.enabled: true

extension:
  datasource:
    default:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username:
      password:
    system:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:system;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username:
      password:
  hibernate:
    default:
      dialect: org.hibernate.dialect.H2Dialect
      packageToScan: sample.model
      showSql: true
      createDrop: true
    system:
      dialect: org.hibernate.dialect.H2Dialect
      packageToScan: sample.context
      showSql: true
      createDrop: true
  security.enabled: false
  mail.enabled: false
  datafixture.enabled: true

---
spring:
  profiles: production

management.security.enabled: true

extension:
  datasource:
    default:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@xxx.xxx.xxx.xxx:1521:xx
      username: XXXXXX
      password: XXXXXX
    system:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@xxx.xxx.xxx.xxx:1521:xx
      username: XXXXXX
      password: XXXXXX
  hibernate:
    default:
      dialect: org.hibernate.dialect.Oracle10gDialect
    system:
      dialect: org.hibernate.dialect.Oracle10gDialect
  security.cors: false
  datafixture.enabled: false
